#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_0", 16, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("a_1", 16, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("a_2", 16, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("a_3", 16, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("a_4", 16, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("a_5", 16, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("a_6", 16, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("a_7", 16, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("b_0", 16, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("b_1", 16, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("b_2", 16, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("b_3", 16, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("b_4", 16, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("b_5", 16, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("b_6", 16, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("b_7", 16, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("s", 16, hls_out, 16, "ap_vld", "out_data", 1),
	Port_Property("s_ap_vld", 1, hls_out, 16, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "inner_product";
