#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_0_address0", 2, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("a_0_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("a_0_q0", 16, hls_in, 0, "ap_memory", "in_data", 1),
	Port_Property("a_1_address0", 2, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("a_1_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("a_1_q0", 16, hls_in, 1, "ap_memory", "in_data", 1),
	Port_Property("a_2_address0", 2, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("a_2_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("a_2_q0", 16, hls_in, 2, "ap_memory", "in_data", 1),
	Port_Property("a_3_address0", 2, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("a_3_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("a_3_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("a_3_d0", 16, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("a_3_q0", 16, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("a_3_address1", 2, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("a_3_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("a_3_we1", 1, hls_out, 3, "ap_memory", "MemPortWE2", 1),
	Port_Property("a_3_d1", 16, hls_out, 3, "ap_memory", "MemPortDIN2", 1),
	Port_Property("a_3_q1", 16, hls_in, 3, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("b_0_address0", 3, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("b_0_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("b_0_q0", 16, hls_in, 4, "ap_memory", "in_data", 1),
	Port_Property("b_1_address0", 3, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("b_1_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("b_1_q0", 16, hls_in, 5, "ap_memory", "in_data", 1),
	Port_Property("b_2_address0", 3, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("b_2_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("b_2_q0", 16, hls_in, 6, "ap_memory", "in_data", 1),
	Port_Property("b_3_address0", 3, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("b_3_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("b_3_q0", 16, hls_in, 7, "ap_memory", "in_data", 1),
	Port_Property("c_address0", 5, hls_out, 8, "ap_memory", "mem_address", 1),
	Port_Property("c_ce0", 1, hls_out, 8, "ap_memory", "mem_ce", 1),
	Port_Property("c_we0", 1, hls_out, 8, "ap_memory", "mem_we", 1),
	Port_Property("c_d0", 16, hls_out, 8, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "mmul";
